### ISSUE TITLE
The old url for your project's live site can no longer be found

### ISSUE THREAD

**Issue by alberto-rj** [0xabdulkhalid/tic-tac-toe#5]
Hey @0xabdulkhaliq, I believe that because you changed your username
from `0xabdulkhalid` to `0xabdulkhaliq`, you forgot to update the URL for
your project's live site. 

I hope I've helped! You've been an inspiration!

**Comment by 0xabdulkhaliq** [comment]
Hello @alberto-rj 👋🏻 

Thank you for addressing this issue, I resolved them now.

PS: As you said, You're really helped me this time. I owe you.
